import { Language } from "@prisma/client";
import { normalizeLanguage } from "@/lib/locale";
import { prisma } from "@/lib/prisma";
import { recommendedResources } from "@/lib/recommends";

export const adminSectionCopy = {
  EN: {
    workspaceTitle: "Admin workspace",
    workspaceIntro: "Manage the learning catalog, practice prompts, script templates, and curated IK recommendations from one focused control center.",
    coursesNav: "Course Library",
    scenariosNav: "Practice Workspace",
    templatesNav: "Script Studio",
    recommendsNav: "IK Recommends",
    skillArea: "Skill area",
    level: "Level",
    featured: "Featured course",
    published: "Published",
    publicSpeaking: "Public speaking",
    hosting: "Hosting",
    communication: "Communication",
    beginner: "Beginner",
    advanced: "Advanced",
    featuredBadge: "Featured",
    coursesIntro: "Create the course, shape its metadata, and manage every lesson from one focused workspace.",
    scenariosIntro: "Create new practice scenarios, refine the rehearsal guidance, and control which prompts are live for learners.",
    templatesIntro: "Manage the script blueprints that power the studio so tone, language, audience, and structure stay intentional.",
    recommendsIntro: "Edit the curated external resources that power the IK Recommends experience.",
    recommendsTitle: "IK Recommends",
    chooser: "Choose an existing recommendation to edit",
    newLabel: "Create a new recommendation",
    titleEn: "Title (English)",
    titleFr: "Title (French)",
    source: "Source",
    contentType: "Content type",
    category: "Track",
    summaryEn: "Summary (English)",
    summaryFr: "Summary (French)",
    ikNoteEn: "Why IK recommends this (English)",
    ikNoteFr: "Why IK recommends this (French)",
    estimatedLength: "Estimated length",
    thumbnail: "Thumbnail URL",
    sortOrder: "Sort order",
    active: "Active",
    createRecommendation: "Create recommendation",
    updateRecommendation: "Update recommendation",
    deleteRecommendation: "Delete recommendation",
    resetForm: "Reset form",
    recommendationSaved: "Recommendation saved successfully.",
    recommendationFailed: "Unable to save recommendation.",
    recommendationDeleted: "Recommendation deleted.",
    video: "Video",
    article: "Article",
    podcast: "Podcast",
    tool: "Tool",
    presence: "Presence & Confidence",
    voice: "Voice & Delivery",
    storytelling: "Storytelling & Structure",
    audience: "Audience Engagement",
    hostingTrack: "MC / Hosting Skills",
    business: "Business of Speaking",
    existingHint: "Use this editor to create new recommendations or update the spotlight and collection items already showing on the learner page.",
    existingListTitle: "Existing recommendations",
    existingListIntro: "Use this list as a quick reference, then choose any item from the editor dropdown when you want to update it.",
    courseWorkspaceTitle: "Course Library",
    courseWorkspaceIntro: "Create new courses, update the metadata learners see, and build out the lesson flow with video links, descriptions, and lesson order.",
    chooseCourse: "Choose a course to manage",
    createNewCourse: "Create a new course",
    courseTitle: "Course title",
    courseSlug: "Course slug",
    courseDescription: "Course description",
    createCourse: "Create course",
    updateCourse: "Update course",
    deleteCourse: "Delete course",
    courseSaved: "Course saved successfully.",
    courseDeleted: "Course deleted.",
    courseSaveFailed: "Unable to save course.",
    courseDeleteFailed: "Unable to delete course.",
    existingCourses: "Existing courses",
    existingCoursesIntro: "Use this list as a quick reference for what is already live in the catalog.",
    lessonsCount: "Lessons",
    totalDuration: "Total duration",
    openCourse: "Open course",
    metadata: "Metadata",
    draft: "Draft",
    manageLessons: "Manage lessons",
    backToCourseManager: "Back to course manager",
    lessonManager: "Lesson manager",
    lessonManagerIntro: "Add lessons to the selected course, edit the teaching copy, update video links, and control the lesson order.",
    chooseLesson: "Choose a lesson to edit",
    createNewLesson: "Create a new lesson",
    lessonTitle: "Lesson title",
    lessonSlug: "Lesson slug",
    lessonDescription: "Lesson description",
    videoUrl: "Video URL",
    durationMinutes: "Duration (minutes)",
    lessonOrder: "Lesson order",
    createLesson: "Create lesson",
    updateLesson: "Update lesson",
    deleteLesson: "Delete lesson",
    lessonSaved: "Lesson saved successfully.",
    lessonDeleted: "Lesson deleted.",
    lessonSaveFailed: "Unable to save lesson.",
    lessonDeleteFailed: "Unable to delete lesson.",
    noLessonsYet: "No lessons yet. Add the first lesson to start building this course.",
    lessonListTitle: "Lessons in this course",
    lessonListIntro: "Select a lesson below when you want to revise it, or create a new one.",
    practiceWorkspaceTitle: "Practice Workspace",
    practiceWorkspaceIntro: "Shape the practice scenarios learners use before they record, including the rehearsal prompt, slug, and coaching guidance.",
    chooseScenario: "Choose a scenario to manage",
    createNewScenario: "Create a new scenario",
    scenarioTitle: "Scenario title",
    scenarioSlug: "Scenario slug",
    scenarioDescription: "Scenario description",
    scenarioGuidance: "Guidance for the learner",
    scenarioActive: "Active scenario",
    createScenario: "Create scenario",
    updateScenario: "Update scenario",
    deleteScenario: "Delete scenario",
    scenarioSaved: "Scenario saved successfully.",
    scenarioDeleted: "Scenario deleted.",
    scenarioSaveFailed: "Unable to save scenario.",
    scenarioDeleteFailed: "Unable to delete scenario.",
    existingScenarios: "Existing scenarios",
    existingScenariosIntro: "Use this list to review the prompts already live in practice mode.",
    activeBadge: "Active",
    inactiveBadge: "Inactive",
    scriptWorkspaceTitle: "Script Studio",
    scriptWorkspaceIntro: "Manage the reusable script templates tied to each scenario so generated drafts stay on-brand and event-ready.",
    chooseTemplate: "Choose a script template to manage",
    createNewTemplate: "Create a new script template",
    scriptScenario: "Scenario",
    scriptLanguage: "Language",
    scriptTone: "Tone",
    scriptAudience: "Audience",
    scriptTemplateBody: "Template body",
    createTemplate: "Create template",
    updateTemplate: "Update template",
    deleteTemplate: "Delete template",
    templateSaved: "Template saved successfully.",
    templateDeleted: "Template deleted.",
    templateSaveFailed: "Unable to save template.",
    templateDeleteFailed: "Unable to delete template.",
    existingTemplates: "Existing templates",
    existingTemplatesIntro: "Use this list to review and refine the script structures already available in the studio."
  },
  FR: {
    workspaceTitle: "Espace admin",
    workspaceIntro: "Gerez le catalogue de formation, les prompts de pratique, les modeles de scripts et les recommandations IK depuis un seul espace clair.",
    coursesNav: "Bibliotheque de cours",
    scenariosNav: "Espace de pratique",
    templatesNav: "Studio de scripts",
    recommendsNav: "IK Recommends",
    skillArea: "Domaine",
    level: "Niveau",
    featured: "Cours en vedette",
    published: "Publie",
    publicSpeaking: "Prise de parole",
    hosting: "Animation",
    communication: "Communication",
    beginner: "Debutant",
    advanced: "Avance",
    featuredBadge: "En vedette",
    coursesIntro: "Creez le cours, ajustez ses metadonnees et gerez chaque lecon depuis un seul espace de travail.",
    scenariosIntro: "Creez de nouveaux scenarios de pratique, ajustez les consignes et controlez quels prompts sont visibles pour les apprenants.",
    templatesIntro: "Gerez les modeles de scripts du studio pour garder une structure, un ton, une langue et une audience coherents.",
    recommendsIntro: "Modifiez les ressources externes choisies qui alimentent l'experience IK Recommends.",
    recommendsTitle: "IK Recommends",
    chooser: "Choisissez une recommandation existante a modifier",
    newLabel: "Creer une nouvelle recommandation",
    titleEn: "Titre (anglais)",
    titleFr: "Titre (francais)",
    source: "Source",
    contentType: "Format",
    category: "Parcours",
    summaryEn: "Resume (anglais)",
    summaryFr: "Resume (francais)",
    ikNoteEn: "Pourquoi IK recommande ceci (anglais)",
    ikNoteFr: "Pourquoi IK recommande ceci (francais)",
    estimatedLength: "Duree estimee",
    thumbnail: "URL de miniature",
    sortOrder: "Ordre d'affichage",
    active: "Actif",
    createRecommendation: "Creer la recommandation",
    updateRecommendation: "Mettre a jour la recommandation",
    deleteRecommendation: "Supprimer la recommandation",
    resetForm: "Reinitialiser",
    recommendationSaved: "Recommandation enregistree avec succes.",
    recommendationFailed: "Impossible d'enregistrer la recommandation.",
    recommendationDeleted: "Recommandation supprimee.",
    video: "Video",
    article: "Article",
    podcast: "Podcast",
    tool: "Outil",
    presence: "Presence et confiance",
    voice: "Voix et delivery",
    storytelling: "Storytelling et structure",
    audience: "Engagement du public",
    hostingTrack: "Animation et maitrise de ceremonie",
    business: "Business de la prise de parole",
    existingHint: "Utilisez cet editeur pour creer de nouvelles recommandations ou mettre a jour les picks deja visibles sur la page apprenant.",
    existingListTitle: "Recommandations existantes",
    existingListIntro: "Utilisez cette liste comme repere rapide, puis choisissez un element dans le menu deroulant de l'editeur pour le modifier.",
    courseWorkspaceTitle: "Bibliotheque de cours",
    courseWorkspaceIntro: "Creez de nouveaux cours, mettez a jour les metadonnees visibles par les apprenants et construisez les lecons avec videos, descriptions et ordre.",
    chooseCourse: "Choisissez un cours a gerer",
    createNewCourse: "Creer un nouveau cours",
    courseTitle: "Titre du cours",
    courseSlug: "Slug du cours",
    courseDescription: "Description du cours",
    createCourse: "Creer le cours",
    updateCourse: "Mettre a jour le cours",
    deleteCourse: "Supprimer le cours",
    courseSaved: "Cours enregistre avec succes.",
    courseDeleted: "Cours supprime.",
    courseSaveFailed: "Impossible d'enregistrer le cours.",
    courseDeleteFailed: "Impossible de supprimer le cours.",
    existingCourses: "Cours existants",
    existingCoursesIntro: "Utilisez cette liste comme repere rapide pour voir ce qui existe deja dans le catalogue.",
    lessonsCount: "Lecons",
    totalDuration: "Duree totale",
    openCourse: "Ouvrir le cours",
    metadata: "Metadonnees",
    draft: "Brouillon",
    manageLessons: "Gerer les lecons",
    backToCourseManager: "Retour au gestionnaire de cours",
    lessonManager: "Gestion des lecons",
    lessonManagerIntro: "Ajoutez des lecons au cours selectionne, modifiez le contenu pedagogique, mettez a jour les liens video et pilotez l'ordre des lecons.",
    chooseLesson: "Choisissez une lecon a modifier",
    createNewLesson: "Creer une nouvelle lecon",
    lessonTitle: "Titre de la lecon",
    lessonSlug: "Slug de la lecon",
    lessonDescription: "Description de la lecon",
    videoUrl: "URL de la video",
    durationMinutes: "Duree (minutes)",
    lessonOrder: "Ordre de la lecon",
    createLesson: "Creer la lecon",
    updateLesson: "Mettre a jour la lecon",
    deleteLesson: "Supprimer la lecon",
    lessonSaved: "Lecon enregistree avec succes.",
    lessonDeleted: "Lecon supprimee.",
    lessonSaveFailed: "Impossible d'enregistrer la lecon.",
    lessonDeleteFailed: "Impossible de supprimer la lecon.",
    noLessonsYet: "Aucune lecon pour le moment. Ajoutez la premiere lecon pour commencer ce cours.",
    lessonListTitle: "Lecons de ce cours",
    lessonListIntro: "Selectionnez une lecon ci-dessous quand vous voulez la modifier, ou creez-en une nouvelle.",
    practiceWorkspaceTitle: "Espace de pratique",
    practiceWorkspaceIntro: "Structurez les scenarios de pratique que les apprenants utilisent avant d'enregistrer, avec le prompt, le slug et les consignes de coaching.",
    chooseScenario: "Choisissez un scenario a gerer",
    createNewScenario: "Creer un nouveau scenario",
    scenarioTitle: "Titre du scenario",
    scenarioSlug: "Slug du scenario",
    scenarioDescription: "Description du scenario",
    scenarioGuidance: "Consignes pour l'apprenant",
    scenarioActive: "Scenario actif",
    createScenario: "Creer le scenario",
    updateScenario: "Mettre a jour le scenario",
    deleteScenario: "Supprimer le scenario",
    scenarioSaved: "Scenario enregistre avec succes.",
    scenarioDeleted: "Scenario supprime.",
    scenarioSaveFailed: "Impossible d'enregistrer le scenario.",
    scenarioDeleteFailed: "Impossible de supprimer le scenario.",
    existingScenarios: "Scenarios existants",
    existingScenariosIntro: "Utilisez cette liste pour revoir les prompts deja visibles dans l'espace pratique.",
    activeBadge: "Actif",
    inactiveBadge: "Inactif",
    scriptWorkspaceTitle: "Studio de scripts",
    scriptWorkspaceIntro: "Gerez les modeles de scripts relies a chaque scenario pour que les brouillons generes restent coherents et prets a l'usage.",
    chooseTemplate: "Choisissez un modele de script a gerer",
    createNewTemplate: "Creer un nouveau modele de script",
    scriptScenario: "Scenario",
    scriptLanguage: "Langue",
    scriptTone: "Ton",
    scriptAudience: "Audience",
    scriptTemplateBody: "Corps du modele",
    createTemplate: "Creer le modele",
    updateTemplate: "Mettre a jour le modele",
    deleteTemplate: "Supprimer le modele",
    templateSaved: "Modele enregistre avec succes.",
    templateDeleted: "Modele supprime.",
    templateSaveFailed: "Impossible d'enregistrer le modele.",
    templateDeleteFailed: "Impossible de supprimer le modele.",
    existingTemplates: "Modeles existants",
    existingTemplatesIntro: "Utilisez cette liste pour revoir et ajuster les structures de scripts deja disponibles dans le studio."
  }
} as const;

export const skillAreaLabels = {
  EN: {
    PUBLIC_SPEAKING: "Public speaking",
    HOSTING: "Hosting",
    COMMUNICATION: "Communication"
  },
  FR: {
    PUBLIC_SPEAKING: "Prise de parole",
    HOSTING: "Animation",
    COMMUNICATION: "Communication"
  }
} as const;

export const levelLabels = {
  EN: {
    BEGINNER: "Beginner",
    ADVANCED: "Advanced"
  },
  FR: {
    BEGINNER: "Debutant",
    ADVANCED: "Avance"
  }
} as const;

export async function ensureRecommendationsSeeded() {
  const count = await prisma.recommendationResource.count();
  if (count > 0) return;

  await prisma.recommendationResource.createMany({
    data: recommendedResources.map((resource, index) => ({
      titleEn: resource.title.EN,
      titleFr: resource.title.FR,
      source: resource.source,
      contentType: resource.contentType,
      category: resource.category,
      summaryEn: resource.summary.EN,
      summaryFr: resource.summary.FR,
      ikNoteEn: resource.ikNote.EN,
      ikNoteFr: resource.ikNote.FR,
      estimatedLength: resource.estimatedLength,
      url: resource.url,
      thumbnail: resource.thumbnail,
      featured: resource.featured,
      active: true,
      sortOrder: index
    }))
  });
}

export async function getAdminContext(userLanguage: Language) {
  const language = normalizeLanguage(userLanguage);
  return {
    language,
    copy: adminSectionCopy[language]
  };
}
