import { SupportedLanguage } from "@/lib/locale";

const dashboardCopy = {
  EN: {
    headline: "You're getting better. Let's keep going.",
    support: "Stay with your current course and keep building momentum one lesson at a time.",
    recommendedHeadline: "Your next step starts here.",
    recommendedSupport: "Start with a recommended course and build your confidence from the ground up.",
    continueLesson: "Continue lesson",
    startRecommendedLesson: "Start this lesson",
    startRecommendedCourse: "Start this course",
    startPractice: "Start practice",
    currentFocus: "Current focus",
    recommendedForYou: "Recommended for you",
    activeCourse: "Active course",
    recommendedCourse: "Recommended course",
    currentLesson: "Current lesson",
    courseProgress: "Course progress",
    latestPracticeScore: "Latest practice score",
    languagePreference: "Language",
    progressSummary: "Progress this week",
    practiceCompleted: "Practice completed",
    latestImprovement: "Latest improvement",
    latestCoachingScore: "Latest coaching score",
    continueLearning: "Continue learning",
    viewAllCourses: "View all courses",
    latestCoachingReview: "Take a practice test",
    recommendsEyebrow: "IK Recommends",
    recommendsSubtitle: "These handpicked lessons, talks, articles, and tools help you sharpen your craft beyond the core IK lessons.",
    recommendsCta: "Explore IK's Recommendations",
    fromLastPractice: "From your last practice",
    topTipToImproveNext: "Top tip to improve next",
    viewFullFeedback: "View full feedback",
    practiceAgain: "Start practice",
    quickActions: "Quick actions",
    startPracticeSession: "Start a practice session",
    startPracticeDescription: "Record a fresh delivery and get coaching on what to improve next.",
    generateScript: "Generate a script",
    generateScriptDescription: "Build a room-ready draft for your next event, intro, or special moment.",
    browseCourses: "Browse courses",
    browseCoursesDescription: "Explore lessons that sharpen your presence, structure, and hosting flow.",
    exploreCourses: "Explore courses",
    openStudio: "Open Script Studio",
    improvementTitle: "Your speaking is improving",
    confidenceTrend: "Confidence",
    clarityTrend: "Clarity",
    paceTrend: "Pace",
    up: "up",
    improving: "improving",
    needsWork: "needs work",
    steady: "steady",
    noActiveCourse: "Choose a course to set your learning focus.",
    beginLearningPath: "Browse courses",
    noCoachingYet: "Take a practice test and unlock coaching.",
    firstPracticeNudge: "Record a short response, and we'll turn it into focused feedback you can use right away.",
    firstPracticePreview: "You'll get feedback on confidence, clarity, and pace.",
    noImprovementData: "Complete another practice to unlock speaking trends.",
    lessonsCompleted: "Lessons completed"
  },
  FR: {
    headline: "Vous progressez. Continuons.",
    support: "Restez sur votre cours actuel et continuez a avancer une lecon a la fois.",
    recommendedHeadline: "Votre prochaine etape commence ici.",
    recommendedSupport: "Commencez par un cours recommande et construisez votre confiance depuis la base.",
    continueLesson: "Continuer la lecon",
    startRecommendedLesson: "Commencer cette lecon",
    startRecommendedCourse: "Commencer ce cours",
    startPractice: "Commencer la pratique",
    currentFocus: "Priorite du moment",
    recommendedForYou: "Recommande pour vous",
    activeCourse: "Cours actif",
    recommendedCourse: "Cours recommande",
    currentLesson: "Lecon actuelle",
    courseProgress: "Progression du cours",
    latestPracticeScore: "Dernier score de pratique",
    languagePreference: "Langue",
    progressSummary: "Progression recente",
    practiceCompleted: "Pratiques terminees",
    latestImprovement: "Derniere progression",
    latestCoachingScore: "Dernier score de coaching",
    continueLearning: "Continuer l'apprentissage",
    viewAllCourses: "Voir tous les cours",
    latestCoachingReview: "Passez un test pratique",
    recommendsEyebrow: "IK Recommends",
    recommendsSubtitle: "Ces lecons, talks, articles et outils choisis avec soin vous aident a aller plus loin que les lecons IK du coeur de la plateforme.",
    recommendsCta: "Explorer les recommandations d'IK",
    fromLastPractice: "Depuis votre derniere pratique",
    topTipToImproveNext: "Conseil principal pour la suite",
    viewFullFeedback: "Voir le retour complet",
    practiceAgain: "Commencer la pratique",
    quickActions: "Actions rapides",
    startPracticeSession: "Lancer une pratique",
    startPracticeDescription: "Enregistrez une nouvelle prise et recevez un coaching clair sur la suite.",
    generateScript: "Generer un script",
    generateScriptDescription: "Creez un brouillon pret pour la salle, l'evenement ou votre prochaine prise de parole.",
    browseCourses: "Parcourir les cours",
    browseCoursesDescription: "Explorez des lecons pour renforcer votre presence, votre structure et votre aisance.",
    exploreCourses: "Explorer les cours",
    openStudio: "Ouvrir le studio",
    improvementTitle: "Votre parole progresse",
    confidenceTrend: "Confiance",
    clarityTrend: "Clarte",
    paceTrend: "Rythme",
    up: "en hausse",
    improving: "en progression",
    needsWork: "a travailler",
    steady: "stable",
    noActiveCourse: "Choisissez un cours pour definir votre priorite.",
    beginLearningPath: "Voir les cours",
    noCoachingYet: "Passez un test pratique et debloquez votre coaching.",
    firstPracticeNudge: "Enregistrez une courte reponse, et nous la transformerons en retour cible que vous pourrez utiliser tout de suite.",
    firstPracticePreview: "Vous recevrez un retour sur la confiance, la clarte et le rythme.",
    noImprovementData: "Faites une autre pratique pour debloquer vos tendances de progression.",
    lessonsCompleted: "Lecons terminees"
  }
} as const;

export type DashboardCopy = (typeof dashboardCopy)[SupportedLanguage];

export function getDashboardCopy(language: SupportedLanguage): DashboardCopy {
  return dashboardCopy[language];
}
